import { useState, useEffect } from 'react';
import { supabase } from '@/integrations/supabase/client';
import type { TablesInsert } from '@/integrations/supabase/types';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Button } from '@/components/ui/button';
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Loader2, UserPlus } from 'lucide-react';
import { toast } from 'sonner';
import type { Customer } from './CustomerSearchDialog';

interface Surname {
  id: string;
  description: string;
}

interface CustomerFormDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onSuccess: (customer: Customer) => void;
  companyId: string;
  initialTaxId?: string;
}

export function CustomerFormDialog({
  open,
  onOpenChange,
  onSuccess,
  companyId,
  initialTaxId,
}: CustomerFormDialogProps) {
  const [surnames, setSurnames] = useState<Surname[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [isSaving, setIsSaving] = useState(false);

  const [formData, setFormData] = useState({
    tax_id: '',
    customer_type: 'individual',
    surname_id: '',
    first_name: '',
    last_name: '',
    mobile_phone: '',
    telephone: '',
    email: '',
    address1: '',
    address2: '',
    district: '',
    province: '',
    postal_code: '',
  });

  // Load surnames on mount
  useEffect(() => {
    const fetchSurnames = async () => {
      setIsLoading(true);
      try {
        const { data, error } = await supabase
          .from('surnames')
          .select('id, description')
          .eq('status', 'active')
          .order('no', { ascending: true });

        if (error) throw error;
        setSurnames(data || []);
      } catch (error) {
        console.error('Error fetching surnames:', error);
      } finally {
        setIsLoading(false);
      }
    };

    if (open) {
      fetchSurnames();
    }
  }, [open]);

  // Reset form when dialog opens
  useEffect(() => {
    if (open) {
      setFormData({
        tax_id: initialTaxId || '',
        customer_type: 'individual',
        surname_id: '',
        first_name: '',
        last_name: '',
        mobile_phone: '',
        telephone: '',
        email: '',
        address1: '',
        address2: '',
        district: '',
        province: '',
        postal_code: '',
      });
    }
  }, [open, initialTaxId]);

  const handleSubmit = async () => {
    // Validation
    if (!formData.tax_id.trim()) {
      toast.error('กรุณากรอกเลขประจำตัวผู้เสียภาษี/เลขบัตรประชาชน');
      return;
    }
    if (!formData.first_name.trim()) {
      toast.error('กรุณากรอกชื่อ');
      return;
    }
    if (!formData.last_name.trim()) {
      toast.error('กรุณากรอกนามสกุล');
      return;
    }

    setIsSaving(true);

    try {
      // Check if tax_id already exists for this company
      const { data: existing } = await supabase
        .from('customers')
        .select('id')
        .eq('company_id', companyId)
        .eq('tax_id', formData.tax_id)
        .maybeSingle();

      if (existing) {
        toast.error('เลขประจำตัวผู้เสียภาษีนี้มีอยู่ในระบบแล้ว');
        setIsSaving(false);
        return;
      }

      // Insert new customer - no and customer_id are auto-generated by database trigger
      const insertData = {
        company_id: companyId,
        tax_id: formData.tax_id,
        customer_type: formData.customer_type,
        surname_id: formData.surname_id || null,
        first_name: formData.first_name,
        last_name: formData.last_name,
        mobile_phone: formData.mobile_phone || null,
        telephone: formData.telephone || null,
        email: formData.email || null,
        address1: formData.address1 || null,
        address2: formData.address2 || null,
        district: formData.district || null,
        province: formData.province || null,
        postal_code: formData.postal_code || null,
        status: 'active',
      } as TablesInsert<'customers'>;

      const { data: newCustomer, error } = await supabase
        .from('customers')
        .insert(insertData)
        .select('*, surnames(id, description)')
        .single();

      if (error) throw error;

      toast.success('เพิ่มลูกค้าใหม่สำเร็จ');
      onSuccess(newCustomer as Customer);
    } catch (error) {
      console.error('Error creating customer:', error);
      toast.error('ไม่สามารถบันทึกข้อมูลได้');
    } finally {
      setIsSaving(false);
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-2xl max-h-[90vh] flex flex-col">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <UserPlus className="w-5 h-5" />
            เพิ่มลูกค้าใหม่
          </DialogTitle>
        </DialogHeader>

        {isLoading ? (
          <div className="flex items-center justify-center py-8">
            <Loader2 className="w-6 h-6 animate-spin" />
          </div>
        ) : (
          <div className="space-y-4 py-4 overflow-y-auto flex-1">
            {/* Tax ID */}
            <div className="space-y-2">
              <Label>
                เลขประจำตัวผู้เสียภาษี/เลขบัตรประชาชน <span className="text-destructive">*</span>
              </Label>
              <Input
                value={formData.tax_id}
                onChange={(e) => {
                  const value = e.target.value.replace(/\D/g, '').slice(0, 13);
                  setFormData({ ...formData, tax_id: value });
                }}
                placeholder="กรอกเลข 13 หลัก"
                maxLength={13}
                className="max-w-xs"
              />
            </div>

            {/* Customer Type */}
            <div className="space-y-2">
              <Label>ประเภทลูกค้า <span className="text-destructive">*</span></Label>
              <RadioGroup
                value={formData.customer_type}
                onValueChange={(v) => setFormData({ ...formData, customer_type: v })}
                className="flex gap-4"
              >
                <div className="flex items-center space-x-2">
                  <RadioGroupItem value="individual" id="cf-individual" />
                  <Label htmlFor="cf-individual" className="cursor-pointer">บุคคลธรรมดา</Label>
                </div>
                <div className="flex items-center space-x-2">
                  <RadioGroupItem value="corporate" id="cf-corporate" />
                  <Label htmlFor="cf-corporate" className="cursor-pointer">นิติบุคคล</Label>
                </div>
              </RadioGroup>
            </div>

            {/* Name Fields */}
            <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
              <div className="space-y-2">
                <Label>คำนำหน้า</Label>
                <Select
                  value={formData.surname_id}
                  onValueChange={(v) => setFormData({ ...formData, surname_id: v })}
                >
                  <SelectTrigger>
                    <SelectValue placeholder="เลือก" />
                  </SelectTrigger>
                  <SelectContent>
                    {surnames.map((s) => (
                      <SelectItem key={s.id} value={s.id}>
                        {s.description}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
              <div className="space-y-2 md:col-span-1">
                <Label>ชื่อ <span className="text-destructive">*</span></Label>
                <Input
                  value={formData.first_name}
                  onChange={(e) => setFormData({ ...formData, first_name: e.target.value })}
                  placeholder="ชื่อ"
                />
              </div>
              <div className="space-y-2 md:col-span-2">
                <Label>นามสกุล <span className="text-destructive">*</span></Label>
                <Input
                  value={formData.last_name}
                  onChange={(e) => setFormData({ ...formData, last_name: e.target.value })}
                  placeholder="นามสกุล"
                />
              </div>
            </div>

            {/* Contact Fields */}
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              <div className="space-y-2">
                <Label>เบอร์มือถือ</Label>
                <Input
                  value={formData.mobile_phone}
                  onChange={(e) => setFormData({ ...formData, mobile_phone: e.target.value })}
                  placeholder="0XX-XXX-XXXX"
                />
              </div>
              <div className="space-y-2">
                <Label>เบอร์โทรศัพท์</Label>
                <Input
                  value={formData.telephone}
                  onChange={(e) => setFormData({ ...formData, telephone: e.target.value })}
                  placeholder="0XX-XXX-XXXX"
                />
              </div>
              <div className="space-y-2">
                <Label>อีเมล</Label>
                <Input
                  type="email"
                  value={formData.email}
                  onChange={(e) => setFormData({ ...formData, email: e.target.value })}
                  placeholder="email@example.com"
                />
              </div>
            </div>

            {/* Address Fields */}
            <div className="space-y-4 pt-2">
              <Label className="text-base font-medium">ที่อยู่</Label>
              <div className="space-y-2">
                <Label className="text-sm text-muted-foreground">ที่อยู่ (บรรทัดที่ 1)</Label>
                <Input
                  value={formData.address1}
                  onChange={(e) => setFormData({ ...formData, address1: e.target.value })}
                  placeholder="เลขที่ ซอย ถนน"
                />
              </div>
              <div className="space-y-2">
                <Label className="text-sm text-muted-foreground">ที่อยู่ (บรรทัดที่ 2)</Label>
                <Input
                  value={formData.address2}
                  onChange={(e) => setFormData({ ...formData, address2: e.target.value })}
                  placeholder="หมู่ ตำบล/แขวง"
                />
              </div>
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                <div className="space-y-2">
                  <Label className="text-sm text-muted-foreground">อำเภอ/เขต</Label>
                  <Input
                    value={formData.district}
                    onChange={(e) => setFormData({ ...formData, district: e.target.value })}
                    placeholder="อำเภอ/เขต"
                  />
                </div>
                <div className="space-y-2">
                  <Label className="text-sm text-muted-foreground">จังหวัด</Label>
                  <Input
                    value={formData.province}
                    onChange={(e) => setFormData({ ...formData, province: e.target.value })}
                    placeholder="จังหวัด"
                  />
                </div>
                <div className="space-y-2">
                  <Label className="text-sm text-muted-foreground">รหัสไปรษณีย์</Label>
                  <Input
                    value={formData.postal_code}
                    onChange={(e) => {
                      const value = e.target.value.replace(/\D/g, '').slice(0, 5);
                      setFormData({ ...formData, postal_code: value });
                    }}
                    placeholder="XXXXX"
                    maxLength={5}
                  />
                </div>
              </div>
            </div>
          </div>
        )}

        <DialogFooter>
          <Button variant="outline" onClick={() => onOpenChange(false)}>
            ยกเลิก
          </Button>
          <Button onClick={handleSubmit} disabled={isSaving}>
            {isSaving ? (
              <>
                <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                กำลังบันทึก...
              </>
            ) : (
              'บันทึก'
            )}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
