-- Create sub_models table
CREATE TABLE public.sub_models (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  no INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  model_id UUID NOT NULL REFERENCES public.models(id) ON DELETE CASCADE,
  description TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'active',
  company_id TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Enable Row Level Security
ALTER TABLE public.sub_models ENABLE ROW LEVEL SECURITY;

-- Create RLS policies
CREATE POLICY "Users can view sub_models from their company"
ON public.sub_models
FOR SELECT
USING (company_id = get_user_company_id(auth.uid()));

CREATE POLICY "Users can create sub_models for their company"
ON public.sub_models
FOR INSERT
WITH CHECK (company_id = get_user_company_id(auth.uid()));

CREATE POLICY "Users can update sub_models from their company"
ON public.sub_models
FOR UPDATE
USING (company_id = get_user_company_id(auth.uid()));

CREATE POLICY "Users can delete sub_models from their company"
ON public.sub_models
FOR DELETE
USING (company_id = get_user_company_id(auth.uid()));

-- Create trigger for updated_at
CREATE TRIGGER update_sub_models_updated_at
BEFORE UPDATE ON public.sub_models
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();